### ISSUE TITLE
App crashes when pressing auto handshake toggle switch a few times in a short timeframe

### ISSUE THREAD

**Issue by geekazoid-at** [austrianredcross/stopp-corona-android#44] opened 2020-05-07 18:58 UTC
## Description

App crashes when pressing auto handshake toggle switch a few times in a short timeframe. 
I reported this issue to the red cross, as well as various times via the Android built in crash reporting dialog and via play store review.

I thought people that work(ed) on sentry are part of the project?! Is anyone monitoring crash reports? This seems to be a tiny problem which could be fixed in a breeze.

I'm not asking to troll, I'm asking to understand possible problems in the process and to learn from your mistakes. I know it's not the most serious problem in the world, but it doesn't look good and doesn't scream quality.

## Reproduction steps

1. Press auto handshake toggle switch.
2. Press auto handshake toggle switch.
3. Press auto handshake toggle switch.
4. Press auto handshake toggle switch.
5. Press auto handshake toggle switch.

Additional helpful information:

- Screenshots: Not needed.
- Version of the app: Current play store version as of 7th of May 2020. First report sent about 4 weeks ago.

## What did you expect

I expect the app not to crash when using the auto handshake toggle button.

**Comment by mitsuhiko** [comment] 2020-05-07 21:29
Thanks for the report!

> I thought people that work(ed) on sentry are part of the project?! Is anyone monitoring crash reports? This seems to be a tiny problem which could be fixed in a breeze.

It's just me that is helping out with Open Sourcing a bit here. Not a developer on this project :) There is currently no crash reporting solution integrated into the current version but maybe this can be changed.

Sounds like this should be easy to reproduce though.

**Comment by marandaneto** [comment] 2020-05-08 11:34
> It's just me that is helping out with Open Sourcing a bit here. Not a developer on this project :) There is currently no crash reporting solution integrated into the current version but maybe this can be changed.

time to clean it up then:

https://github.com/austrianredcross/stopp-corona-android/blob/51c5ec1df1d63c23e24af338068b55d83a2e4c51/app/build.gradle#L101-L102

https://github.com/austrianredcross/stopp-corona-android/blob/770e63a5f9de340c5016fd13a88de9028a7d4100/app/proguard-rules.pro#L60-L64

**Comment by MovGP0** [comment] 2020-06-03 09:26
@mitsuhiko I think the crash reporting was not included for privacy concerns.

**Comment by MovGP0** [comment] 2020-06-03 09:28
there are multiple solutions to prevent a button from beeing pressed too often. One way is to disable the button on the first tap (for some time) on the UI thread while executing the request in the background. Another way is to redirect the user to a different view without the button (similar to [POST-REDIRECT-GET](https://en.wikipedia.org/wiki/Post/Redirect/Get)).

**Comment by marandaneto** [comment] 2020-06-03 10:09
they use RxJava so it'd be easy to do something like:

```
RxView.clicks(view)
  .debounce(...) // or throttle...
  // observe
  .subscribe(..)
```

**Comment by marandaneto** [comment] 2020-06-26 13:37
I can't reproduce it on the latest version, I think it's fixed.

**Comment by mitsuhiko** [comment] 2020-06-26 13:52
Closing this as resolved.

**Closed by mitsuhiko** 2020-06-26 13:52 UTC
Labels: bug, good first issue
