### ISSUE TITLE
Update crashes the app

### ISSUE THREAD

**Issue by MidnightDesign** [austrianredcross/stopp-corona-android#178] opened 2020-06-26 06:21 UTC
I had the old version of the app installed and updated to the new version via the Play Store. When I tried to open the app, it crashed immediately. (Showing the "crashed app" dialog box for half a second.) This happened every time I tried to open it.

I had to uninstall and reinstall the app to get it working.

I could reproduce the bug on both a Pixel 2 and a Pixel 3a.

I've managed to tap the "Report" button in the short time it was there and you should see a report from about half an hour ago on a Pixel 2.

**Comment by MovGP0** [comment] 2020-06-26 06:30
Same issue here. Pixel 3 XL / Android 11. Uninstalling and reinstalling the app solved the issue. Just stopping and restarting the app did not help.

**Comment by OttoWinter** [comment] 2020-06-26 06:32
Seeing this as well. The issue is in the DB upgrade process as can be seen in the stacktrace (includes TableInfo and onIpgrade in the stacktrace). Unfortunately I don't have the stacktrace anymore but it should be easy to reproduce.

Deleting the app data + restarting the app fixed the issue, but it's obviously not ideal.

I don't understand how this issue could have slipped past testing (have observed the issue for n=4 devices).

**Comment by WalternativE** [comment] 2020-06-26 06:47
Saw this happening for me as well (Nokia 8 on Android 9). Can confirm that @OttoWinter's workaround resolves the problem.

**Comment by mitsuhiko** [comment] 2020-06-26 07:03
Thanks for the report. I have forwarded this to make sure this is being addressed. For now it would appear the deinstallation/reinstallation is the best workaround.

**Comment by PeterTheOne** [comment] 2020-06-26 08:05
Had the same issue. Forcing the app to stop and deleting cache and all other storage worked for me.

**Comment by cip** [comment] 2020-06-26 09:03
I've observed the same issue on a samsung note 8. Could be solved by uninstalling and then installing again.

**Comment by jensens** [comment] 2020-06-26 12:44
Same here, OnePlus Two with LineageOS 16/Android 9

**Comment by uliluckas** [comment] 2020-06-29 06:50
Fixed in 2.0.3

**Closed as completed by uliluckas** 2020-06-29 06:50 UTC
Labels: bug
