### ISSUE TITLE
Not compatible with Samsung Galaxy S7 and S7 edge

### ISSUE THREAD

**Issue by DaRoli** [austrianredcross/stopp-corona-android#179] opened 2020-06-26 08:07 UTC
## Description
Tried to install the Corona app over the Android App store -> Not compatible ("Diese App ist mit keinem deiner Geräte kompatibel.") Same on two phones (Samsung Galaxy S7 and Samsung Galaxy S7 Edge).

## Reproduction steps

1. Go to Android app store (https://play.google.com/store/apps/details?id=at.roteskreuz.stopcorona) and wanted to install the current version (2.0.0.1049-QA_240 from 2020-06-25)

Additional helpful information:
Android 8.0.0
Samsung Experience-Version 9.0

## What did you expect
That I can install the app.

**Comment by marandaneto** [comment] 2020-06-26 08:29
does your device support BLE? the Manifest requires `android.hardware.bluetooth_le`, just guessing here.

**Comment by treysis** [comment] 2020-06-26 11:11
Probably you're not using Austrian PlayStore.

**Comment by mitsuhiko** [comment] 2020-06-26 13:12
Closing this as likely duplicate of #150.

**Closed as completed by mitsuhiko** 2020-06-26 13:12 UTC

**Comment by DaRoli** [comment] 2020-06-26 16:07
Yes, that was indeed a duplicate. Switched now from the German to the Austrian profile.
I was not aware, that this country profile exists.
Perhaps you should consider to mention this in some FAQ/Troubleshooting.
Thanks for your help.
